### ISSUE TITLE
Add JUnit reporter

### ISSUE THREAD

**Issue by r0b3rtk** [Eernie/JMoribus#28]
Add implementation for a reporter that outputs JUnit XML.

**Comment by Eernie** [comment]
Yes we have to make a custom JunitRunner.
I'd suggest to create a view looking like the jbehave junit runner
https://github.com/codecentric/jbehave-junit-runner

**Comment by r0b3rtk** [comment]
This XSD seems to be a good description of the JUnit XML format as generated by the JUnit ant task:

http://windyroad.com.au/dl/Open%20Source/JUnit.xsd

Although it is not complete, see: https://windyroad.zendesk.com/entries/56354186-Your-open-source-JUnit-XSD

**Comment by Eernie** [comment]
why would we want to use this xsd? With the annotation `@RunWith` we can give a Reporter that creates the xml via the Junit api.

**Comment by Eernie** [comment]
I stand corrected, the runWith method does not result in a Junit rusult xml, If we really want this feature we'll have to generate one our self.
